### ISSUE TITLE
use custom declarators to set up typestates

### ISSUE THREAD

**Issue by trosel** [jonathanstowe/Tinky#2]
a la [this blog post](http://olleharstedt.github.io/fstar/2017/01/12/typestate-in-fstar.html), it may be possible to create something that looks like this example:

```
state File {
  public final String filename;
}

state OpenFile extends File {
  private CFilePtr filePtr;
  public int read() { ... }
  public void close() [OpenFile>>ClosedFile] { ... }
}

state ClosedFile extends File {
  public void open() [ClosedFile>>OpenFile] { ... }
}
```

So I was thinking with Tinky, we could have custom declarators like

```perl6
workflow File {
  has @!states;
  has @!transitions;
}
state Open extends File {
}
state Closed extends File {
}
transition Open-Closed does Open does Closed {
}
```

Just brainstorming.

**Comment by jonathanstowe** [comment]
I have considered something similar , I'm quite happy for someone to implement something like this as a separate module rather than putting it in the Tinky itself.

Though my prefered style would be something more like the Scala FSM http://doc.akka.io/docs/akka/current/scala/fsm.html for the declarations (though obviously with the syntax adjusted to be Perl 6, can't use extends there without actually changing the language.)

Perhaps a more natural declaration would be something like:

```perl6
workflow Foo {
   state Bar {
   }
  state Baz {
  }
  transition BarToBaz[Bar, Baz] {
  }
}
```

Without any need to overload the meaning of any traits artificially.  Quite easily doable with $EXPORTHOW::DECLARE and so forth, the tricky is the discovery of the inner states and transitions.
